spring:
  application:
    name: mcc-tienda-demo

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: false

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    user:
      name: rob
      password: 123

server:
  port: 9090

version:
  api: /api/1.0.0


