spring:
  application:
    name: mcc-tienda-demo
  datasource:
    url: jdbc:mysql://localhost:3306/tienda_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: "" # o tu contrase√±a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

version:
  api: /api/1.0.0
